modLoader="javafml"
loaderVersion="[48,)"
license="All rights reserved"
[[mods]]
modId="luckytntmod"
version="3.1"
displayName="Lucky TNT Mod"
logoFile="logo.png"
credits="Created by SlimingHD and Fleshcrafter"
description='''
Lucky TNT adds tons of new TNT to destroy your world with!
'''
[[dependencies.luckytntmod]]
    modId="forge"
    mandatory=true
    versionRange="[48,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.20.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntmod]]
	modId="luckytntlib"
	mandatory=true
	versionRange="[48.0.19.0,)"
	ordering="NONE"
	side="BOTH"
